image: node:alpine

stages:
  - test
  - deploy

tests-and-coverage:
  stage: test
  script:
    - npm install --include=dev
    - npm test
  coverage: /Lines\s*:\s*(\d+.?\d*)%/
  artifacts:
    paths:
      - coverage/

deploy-with-serverless:
  only:
    - master
  services:
    - docker:dind
  image: docker:latest
  stage: deploy
  before_script:
    - apk --update add nodejs npm
  script:
    - npm install -g serverless
    - npm install -g serverless-scaleway-functions
    - serverless deploy
    
pages:
  only:
    - master
  stage: deploy
  dependencies:
    - tests-and-coverage
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
